baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Chase Dylan McNeill"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Worksheets"
    url = "/worksheets/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
  [[menu.main]]
    name = "Failure Journal"
    url = "/failure_journals/"
    weight = 5
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
  