baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Chase McNeill Professional Development Website"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Issues"
    url = "/issues/"
    weight = 3
  [[menu.main]]
    name = "Worksheets"
    url = "/worksheets/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4